import Head from 'next/head'
import Image from 'next/image'
import Comment from '../pages/components/comment'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
     
     {/* we can write css on component level with this css modules   */}
      <style jsx>
        {`
          .myImg{
            border-radius: 10px;
            margin:10px;
          }
        `}
    


     

      </style>
      <Comment/>
      <Head>
        <title>Create Blogpost</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
       <script src="" strategy="lazyOnload"></script>


       
       {/* by style jsx we can add css in particular component */}
      <main className={styles.main}>
      
        <h1 className={styles.title}>
          <span className='mySpan'> 
         Coding with Sarita </span>
        </h1>
       <img src="/coder.avif" className='myImg' layout="fill" width={300} height={180}></img>
        <p className={styles.description}>
          A blog for Coders
        </p>
       
        <div className='blogs'>
        <h1>Popular Blogs</h1>
          <div className='blogItem'>
            <h3>How to learn Javascript in 2022?</h3>
             <p>Javascript is the language used to design logic for the web</p>
          </div>
        </div>
        <div className='blogs'>
          <div className='blogItem'>
            <h3>How to learn Javascript in 2022?</h3>
             <p>Javascript is the language used to design logic for the web</p>
          </div>
        </div>
        <div className='blogs'>
          <div className='blogItem'>
            <h3>How to learn Javascript in 2022?</h3>
             <p>Javascript is the language used to design logic for the web</p>
          </div>
        </div>
      
      </main>

      <footer className={styles.footer}>
        Made by Sarita with ❤
      </footer>
    </div>
  )
}
