import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Blogpost</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
       <script src="" strategy="lazyOnload"></script>


       <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Contact</li>
          <li>Blog</li>
        </ul>
       </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
         Coder
        </h1>

        <p className={styles.description}>
          A blog for Coders
        </p>
       
        <div className='blogs'>
        <h2>Popular Blogs</h2>
          <div className='blogItem'>
            <h3>How to learn Javascript in 2022?</h3>
             <p>Javascript is the language used to design logic for the web</p>
          </div>
        </div>
        <div className='blogs'>
          <div className='blogItem'>
            <h3>How to learn Javascript in 2022?</h3>
             <p>Javascript is the language used to design logic for the web</p>
          </div>
        </div>
        <div className='blogs'>
          <div className='blogItem'>
            <h3>How to learn Javascript in 2022?</h3>
             <p>Javascript is the language used to design logic for the web</p>
          </div>
        </div>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        Made by Sarita with ❤
      </footer>
    </div>
  )
}
